@baseUrl = http://localhost:3000

###
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}

###
GET {{baseUrl}}/protected
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4gVXNlciIsImVtYWlsIjoiYWRtaW5AdXNlci5jb20iLCJpYXQiOjE3NjQ4NzA1NTUsImV4cCI6MTc2NDg3MDYxNSwic3ViIjoiMSJ9.hNIeuiC5cvAheUBYAErbe_4BLzvdBR3-Ooyl8WtDeCtQlAkmAHoNGAvY-K2XAfLZv0d0KLfVOpOdVhLYl-SEDXK_NvorXWFR-xGaShEe9vVULMOWYbTyBRRFG71WpKzi7auvSiZIpWIqRfYrhm6gX0vDxWK1Tx211Cw3z5fh0Z53Fiu-A172LM6xCATiLqTDu0NSa1X9Ga83kI0hy096-Q7flzaMsf61UQaQLmz7Lfo3f2UpEVFYpYSqYn8_4lDROshPCo28aPwKIZQGuroNM62J5ADRfqvuO5V4WMiKs2gtqWaWt0mbAqUYjkvrmKC76Eg9iC6jcuaKM7vnV8AQhg