@baseUrl = http://localhost:3000
@adminAccessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4gVXNlciIsImVtYWlsIjoiYWRtaW5AdXNlci5jb20iLCJpYXQiOjE3NTEzMzE3MTksImV4cCI6MTc1MTMzMTc3OSwic3ViIjoiMSJ9.MvzOyydO0Y7qVqV0H52Y9nXUDy94IJTiWffD6lYYfNuP9SnXOLPYkGf6xplq9rjo00XEPsYdh3UAqNZoW_qTThXIXecQYgZNS9AMv8rwJOOvHmllkcjK4cxzrB6Ho0E5Jq1AeZs7sRntKyTTeVQvM_jmbwMwn_FNr5CTi-LnUG3LVOEvOnaZzJb1Cas9_AibZ5iFWqO3lhhGZMKig-21NfDx5vspXk2nooZDyY2mAiNQ_yvCk-sjjI9RnnegmJaBgNd7dDL6Z6mhqlRMZihIkEWZhWbz3Bqzo_6kdPTpfCeo0xnu4LpyfyVRipkwt1lmLmJfLIX3uoV8cXb_yGnZrw

### Create new user
# @name createUserAction
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{adminAccessToken}}

{
    "name": "John Doe",
    "email": "john@example.com",
    "password": "123456"
}

###
@userId = {{ createUserAction.response.body.id }}

### Get user by ID
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{adminAccessToken}}

### Update user
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{adminAccessToken}}

{
    "name": "John Doe Updated",
    "email": "john.updated@example.com",
    "password": "654321"
}

### Delete user
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{adminAccessToken}}