@baseUrl = http://localhost:3000

###
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}

###
GET {{baseUrl}}/protected
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4gVXNlciIsImVtYWlsIjoiYWRtaW5AdXNlci5jb20iLCJpYXQiOjE3NTEzMzE3MTksImV4cCI6MTc1MTMzMTc3OSwic3ViIjoiMSJ9.MvzOyydO0Y7qVqV0H52Y9nXUDy94IJTiWffD6lYYfNuP9SnXOLPYkGf6xplq9rjo00XEPsYdh3UAqNZoW_qTThXIXecQYgZNS9AMv8rwJOOvHmllkcjK4cxzrB6Ho0E5Jq1AeZs7sRntKyTTeVQvM_jmbwMwn_FNr5CTi-LnUG3LVOEvOnaZzJb1Cas9_AibZ5iFWqO3lhhGZMKig-21NfDx5vspXk2nooZDyY2mAiNQ_yvCk-sjjI9RnnegmJaBgNd7dDL6Z6mhqlRMZihIkEWZhWbz3Bqzo_6kdPTpfCeo0xnu4LpyfyVRipkwt1lmLmJfLIX3uoV8cXb_yGnZrw